# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yet Another Blog
# email: dmitry.birin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Simple blog to share thoughts and practice English.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
#twitter_username: dmitrybirin
github_username:  dmitrybirin

# Build settings
include: ['_pages']
kramdown:
  input: GFM
